import { useEffect, useRef, useState } from 'react';
import { Check, Crosshair, FileUp, RotateCcw, ScanLine, X } from 'lucide-react';
export type Detection = { detection_id: string; class_name: string; confidence: number; anomaly_score: number; priority: string; bbox: [number, number, number, number]; estimated_dimensions: string; shadow_length_px: number | null; status: string; geolocation_status: string; inference_mode: string };
type Props = { api: string; onDetection: (item: Detection) => void; onReview: (item: Detection, action: string) => void };
export function AnalyzeView({ api, onDetection, onReview }: Props) {
  const [image, setImage] = useState<string | null>(null); const [detection, setDetection] = useState<Detection | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('LOAD A SIDE-SCAN SONAR IMAGE');
  const input = useRef<HTMLInputElement>(null); const img = useRef<HTMLImageElement>(null); const canvas = useRef<HTMLCanvasElement>(null);
  function draw() { const source = img.current; const target = canvas.current; if (!source || !target) return; const box = target.getBoundingClientRect(); const scale = Math.min(box.width / source.naturalWidth, box.height / source.naturalHeight); target.width = box.width * devicePixelRatio; target.height = box.height * devicePixelRatio; const ctx = target.getContext('2d'); if (!ctx) return; ctx.scale(devicePixelRatio, devicePixelRatio); const w = source.naturalWidth * scale, h = source.naturalHeight * scale, x = (box.width - w) / 2, y = (box.height - h) / 2; ctx.drawImage(source, x, y, w, h); if (detection) { const [a,b,c,d] = detection.bbox; ctx.strokeStyle='#e9b968'; ctx.lineWidth=2; ctx.strokeRect(x+a*scale,y+b*scale,(c-a)*scale,(d-b)*scale); ctx.fillStyle='#e9b968'; ctx.fillRect(x+a*scale,y+b*scale,132,19); ctx.fillStyle='#081015'; ctx.font='11px monospace'; ctx.fillText(`${detection.detection_id} · DEMO`,x+a*scale+5,y+b*scale+13); } }
  useEffect(() => { draw(); window.addEventListener('resize', draw); return () => window.removeEventListener('resize', draw); }, [image, detection]);
  async function upload(file: File) { if (!file.type.startsWith('image/')) { setMessage('UNSUPPORTED FILE — USE PNG, JPEG, OR TIFF'); return; } setImage(URL.createObjectURL(file)); setDetection(null); setBusy(true); setMessage('VALIDATING → PREPROCESSING → SYNTHETIC DEMO ANALYSIS'); try { const form = new FormData(); form.append('file', file); const r = await fetch(`${api}/api/analyze`, {method:'POST',body:form}); const body = await r.json() as { detections?: Detection[]; detail?: string }; if (!r.ok) throw new Error(body.detail); const next = body.detections?.[0]; if (next) { setDetection(next); onDetection(next); setMessage('DEMO CANDIDATE READY — REVIEW REQUIRED'); } } catch (error) { setMessage(`ANALYSIS FAILED — ${error instanceof Error ? error.message : 'LOCAL API UNAVAILABLE'}`); } finally { setBusy(false); } }
  return <section className="analyze"><header className="analyze-head"><div><p className="eyebrow">ANALYZE / INSPECTION WORKSPACE</p><h2>Sonar interpretation bay</h2></div><div className="toolbox"><button onClick={() => input.current?.click()}><FileUp size={15}/> UPLOAD SURVEY</button><span>DEMO ENGINE</span></div></header><div className="workspace"><div className="viewer"><div className="viewer-top"><span className={busy ? 'pulse' : ''}><ScanLine size={15}/> {message}</span><span className="mono">RAW INPUT · 0—30m RANGE</span></div><div className="sonar-stage" onClick={() => !image && input.current?.click()}>{image ? <><img ref={img} src={image} onLoad={draw}/><canvas ref={canvas}/></> : <div className="drop"><Crosshair size={40}/><strong>SONAR VIEWPORT</strong><p>Drop or browse a local image to start a traceable demo workflow.</p></div>}</div><div className="range"><span>PORT</span><i/><span>0m</span><i/><span>10m</span><i/><span>20m</span><i/><span>30m</span><i/><span>STARBOARD</span></div></div><aside className="intel"><p className="eyebrow">DETECTION INTELLIGENCE</p>{detection ? <><div className="id">{detection.detection_id}</div><h3>{detection.class_name}</h3><div className="demo-callout">SYNTHETIC DEMO CANDIDATE<br/><small>Not trained-model inference</small></div><dl><div><dt>Confidence</dt><dd>Unavailable</dd></div><div><dt>Anomaly score</dt><dd>Not assessed</dd></div><div><dt>Dimensions</dt><dd>{detection.estimated_dimensions}</dd></div><div><dt>Shadow</dt><dd>{detection.shadow_length_px ?? 'Not assessed'}</dd></div><div><dt>Location</dt><dd>{detection.geolocation_status}</dd></div></dl><div className="review"><button onClick={() => onReview(detection,'CONFIRM')}><Check size={14}/> CONFIRM</button><button onClick={() => onReview(detection,'REJECT')}><X size={14}/> REJECT</button><button onClick={() => onReview(detection,'RECOVERY_QUEUE')}><RotateCcw size={14}/> RECOVERY QUEUE</button></div></> : <div className="no-selection">No candidate selected.<br/><small>Results are only created after upload.</small></div>}</aside></div><input ref={input} type="file" accept="image/png,image/jpeg,image/tiff" hidden onChange={(e) => { const f=e.target.files?.[0]; if(f) void upload(f); }}/></section>;
}
